### ISSUE TITLE
Feature request: Removing scheduled task

### ISSUE THREAD

**Issue by dbrgn** [fede1024/rust-scheduled-executor#2]
Nice library! :) But is there a way to remove / cancel a scheduled task (besides dropping the executor)?

**Comment by fede1024** [comment]
Now there is :) see [TaskHandle](https://fede1024.github.io/rust-scheduled-executor/scheduled_executor/executor/struct.TaskHandle.html). The implementation is very trivial, but should do the job.

**Comment by dbrgn** [comment]
Awesome, thanks! :) I'll try it out once I find time to continue working on my project, probably by next weekend.

**Comment by fede1024** [comment]
Cool. Happy to release a new version if it works for you.

**Comment by dbrgn** [comment]
A bit late, but: Thanks, works nicely! :+1:
